# TODO set server port
server:
  port: 8082

---
# TODO set datasource
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reggie?useServerPrepStmts=true
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource


---
# TODO set mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id

---
# TODO set path
reggie:
  path: D:\IDEA projects\reggie-take-out\img\

---
# TODO set redis using centos7 server
spring:
  data:
    redis:
      host: 192.168.112.132
      port: 6379
      password: root
      database: 0


